# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.cache/wt [current_project]
set_property parent.project_path F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths f:/ip_repo/myMNIST_CNN_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo f:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/Accumulator.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/BUF1.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/BUF2.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/Bias_ROM.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/Comparator.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/FC_Bias_ROM.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/FC_Controller.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/FC_Layer.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/FIFO.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/MAC.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/MaxPooling_ReLU.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/Max_finder.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/PE.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/PE_Array.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/Sliding_Window.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/new/TDP.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/acc.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/glbl_controller.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/matmul.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/mul.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/single_port_bram.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/top.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/y_buf.v
  F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/imports/cnn/top_cnn.v
}
read_ip -quiet F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all f:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all f:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/constrs_1/imports/01_SoC/Zybo-Z7-Master.xdc
set_property used_in_implementation false [get_files F:/MNIST_CNN_FPGA/MNIST_CNN_FPGA.srcs/constrs_1/imports/01_SoC/Zybo-Z7-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_cnn -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_cnn.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_cnn_utilization_synth.rpt -pb top_cnn_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
